Fixes
verstaburo/iamhero-bootstrap pull request #1
Opened 2017-10-04 23:46 UTC by alege

2017-10-09 13:09 UTC, DimitryKislichenko commented
@procvetov уже прошло 5 дней с пул реквеста, вы не могли бы просмотреть работу и либо принять её, либо указать на ошибки? Спасибо!

2017-10-10 08:32 UTC, procvetov requested changes

2017-10-10 08:32 UTC, procvetov commented on dist/dashboard.html
>              <h3>Please rate Your Experience using iamhero.io! From complete and absolute zero to mindblowing, spectacular happiness!</h3>
Просьба перенести `h3` под `div.page__header-custom`, чтобы получилась такая струкрута:
```
<div class="page__header-custom">
  <h2>I am Hero Survey</h2>
  <h3>Please rate Your Experience using iamhero.io! From complete and absolute zero to mindblowing, spectacular happiness!</h3>
</div>
```
Необходимо для того, чтобы:
1) в админке не создавать два отдельных поля для редактирования;
2) в редактор не попадали блоки с классами - `<div class="page__header-custom">`.

2017-10-10 08:32 UTC, procvetov commented on dist/heroes-to-suggest.html
> +                                <select class="js-select select select_big select_warning" placeholder="Working field">
Тут будет использоваться библиотека select2.

2017-10-10 08:32 UTC, procvetov commented on dist/heroes-to-suggest.html
> +                                <select class="js-select select select_big select_warning" placeholder="Choose profession">
Тут будет использоваться библиотека select2.

2017-10-10 08:32 UTC, procvetov commented on dist/heroes-to-suggest.html
> +                    <div class="inner-plate page__section page__section page__section_lg">
Есть возможность быстро переделать в `div.panel.panel-default`? Если нет - пусть остается, не критично.

2017-10-10 08:32 UTC, procvetov commented on dist/heroes-to-suggest.html
>                                  <input class="form-control form-control-warning" type="text" placeholder="Maximum amount" />
Тут и в остальных местах нужен `form-control-warning` или он оставлен для примера валидации?

2017-10-10 09:14 UTC, alege commented on dist/heroes-to-suggest.html
>                                  <input class="form-control form-control-warning" type="text" placeholder="Maximum amount" />
он нужен, это стилизация по дизайну

2017-10-10 09:14 UTC, alege commented on dist/dashboard.html
>              <h3>Please rate Your Experience using iamhero.io! From complete and absolute zero to mindblowing, spectacular happiness!</h3>
сегодня поправлю

2017-10-10 09:14 UTC, alege commented on dist/heroes-to-suggest.html
> +                                <select class="js-select select select_big select_warning" placeholder="Working field">
сегодня поправлю

2017-10-10 09:16 UTC, alege commented on dist/heroes-to-suggest.html
> +                    <div class="inner-plate page__section page__section page__section_lg">
желательно оставить, во многих местах используется

2017-10-11 09:13 UTC, procvetov requested changes

2017-10-11 09:13 UTC, procvetov commented on dist/hero-search.html
> +                        <div class="inner-card__footer-buttons">
Наведя на героя открывается плашка "Buy Contact", которая пропадает при попытке перейти на нее.

2017-10-11 09:13 UTC, procvetov commented on dist/notification-options.html
> +            <label class="checkbox checkbox-secondary notification-options__item">
Есть возможность использовать стандартную структуру checkbox'ов и radio, а стили и дополнительные враперы добавлять при помощи JS?

2017-10-11 09:13 UTC, procvetov commented on dist/shortlist.html
> +                                <input class="form-control form-control-small form-control-font-standart" type="text" placeholder="New shortlist name" />
Не выглядит как bootstrap форма, не смогли сделать пример валидации.

2017-10-11 14:57 UTC, alege commented on dist/hero-search.html
> +                        <div class="inner-card__footer-buttons">
проверьте еще раз после коммита adaptive & dev, там фиксил карточку и добавил еще одну всплывашку которая после первой формы показывается

2017-10-11 14:57 UTC, alege commented on dist/notification-options.html
> +            <label class="checkbox checkbox-secondary notification-options__item">
буду пробовать

2017-10-11 14:57 UTC, alege commented on dist/shortlist.html
> +                                <input class="form-control form-control-small form-control-font-standart" type="text" placeholder="New shortlist name" />
поправлю

2017-10-16 13:41 UTC, procvetov approved these changes

2017-10-16 13:41 UTC, merged